### ISSUE TITLE
Questions on AAI verus skaai?

### ISSUE THREAD

**Issue by jianshu93** [bluenote-1577/skani#3]
Hello Jim,

Average Amino acid identity (so called AAI), similar to that of ANI but based on amino acid sequences is another way to measure genomic distance smaller than 70~80% ANI. I noticed that skani does support faa (amino acid format as input, predicted via gene prediction software like prodigal/FragGeneScan) kmer processing (and AAI output) but I do not see benchmarks against blastp-based AAI (so alignment based) in the paper. Does it correlate well with blastp based AAI? Since AAI search/alignemnt is much more expensive than ANI, skani will then be another faster tool to approximate blastp-based AAI.

Thanks,

Jianshu

**Comment by bluenote-1577** [comment]
Hi Jianshu, 

Thanks for bringing this interesting point up. I have actually never tried using .faa files with skani.

skani, with it's default parameters, **would not work well for .faa files because the k-mers are too long (k = 15) and the subsampling rate is too high (c = 125)**. k = 15 for amino acids would correspond to k = 45 for the nucleotide case, similarly c = 125 corresponds to c = 375 for amino acids. 

However, I believe that if one were to change the k and c parameters to something more reasonable, it may work. Currently, you can actually set -k as a hidden parameter (I made it hidden because I don't see why one would want to change it for nucleotide inputs), so feel free to try it.  Probably something like k = 6-9, c = 10-30 would work decently well in theory. However, I give no guarantees. 

On a related note, originally skani had a method to take a DNA fasta and do a 6-frame translation to amino acids. We found this worked decently, but it fails on some edge cases, so we have not advertised this feature.  

I'll keep this issue open for now, so if others are curious, they can play around with it.

**Comment by bluenote-1577** [comment]
Hi Jianshu,

skani does not work with .faa files right now. Thanks for bringing up that .faa files are actually supported, I never considered this case. I will patch this in the future. 

In theory, skani's algorithm could work with .faa files, but I would have to change the implementation to recognize .faa files and do testing on default parameters, since skani's default parameter would work poorly. I think this is interesting though, and if I investigate this in the future I'll let you know. 

If you're curious, we originally implemented a 6-frame translation with skani to calculate AAI. We found that this worked decently, but failed for some genomes, so we did not include it in the final release. We never tested with gene prediction software output .faa files, though.

**Comment by jianshu93** [comment]
Hello Jim,

Thanks for letting me know because I saw AAI in the triangle subcommand (-a option).  Therefore this option is just a dummy one right.


Thanks,
Jianshu

**Comment by bluenote-1577** [comment]
Hi Jianshu,

Yes that is my bad, I meant to remove it. I have updated the repo again. I checked and there should be no more AAI mentions in the help commands. 

Thanks very much for your help!

**Comment by bluenote-1577** [comment]
Hi jianshu,

In my experience, fastani will give slightly better rank correlation than skani. There is slightly more variance associated to skani's ANI calculation due to its sparse seeding scheme when the ANIs are very very similar.

**Comment by jianshu93** [comment]
this is consistent with what i observed for the testing dataset.

Thanks for quick response!

Jianshu
