### ISSUE TITLE
calculate ANI for eukaryotes such as fungi 

### ISSUE THREAD

**Issue by neptuneyt** [bluenote-1577/skani#30]
Thank you very much for such a great tool, I have a question, can the tool calculate ANI for eukaryotes such as fungi and if so what are the precautions to be taken?

**Comment by bluenote-1577** [comment]
I've used skani to calculate ANI between eukaryotic genomes recovered from metagenomics (e.g. phytoplankton) and our results were concordant with mummer-based approaches. I'd say go for it. If the genomes are very fragmented, you may benefit from varying the preset --slow, --medium commands, otherwise, defaults should be okay.

**Comment by neptuneyt** [comment]
I'II try. Thanks a lot.

**Comment by neptuneyt** [comment]
Could share your article for me. Thanks a lot.
